#!/usr/bin/env python3
"""The ideal-ramp transient A/B for the soft-start hand-over (issue #246).

    ./sim/soft-start/testbench/ramp_ab.py                  # the named corner set
    ./sim/soft-start/testbench/ramp_ab.py --corners tt --temps -40 \
        --supplies 2.97                                    # one point
    ./sim/soft-start/testbench/ramp_ab.py --help

`design/softstart_injection_compensation.md` section 4 names one open question
and the experiment that settles it: at `tt_-40c_2.97v` the output the main loop
must acquire at hold release differs between the ideal `Binj_ss` element and
issue #191's device chain by **2.1x**, but the capacitor current it acquires it
with differs by **356x**. A 2.1x voltage difference cannot produce a 356x
current difference, so the transient is not the DC transfer defect scaled up --
something in the device build does not track the hold release. The named
experiment is a transient A/B with `V(SSR)` driven by an *ideal ramp source*
through the promoted `SSR` port, which separates the injection element's own
transfer from the ramp node's dynamics.

This is that driver. Two arms per point, on the same deck
(`tb_ss_ramp_ab.spice.in`), differing in exactly one line:

* **`internal`** -- `V(SSR)` generated by the design (`Fss_ramp` into `Css`,
  released by `Mdis_ss`, ceilinged by `Mtop_ss`); the promoted port is left
  unconnected, so this arm is electrically `tb_soft_start.spice.in`.
* **`ideal`** -- `V(SSR)` FORCED by a PWL voltage source on the promoted port.

The PWL is **fitted to the same point's own `internal` arm** (two fixed SSR
crossings, 0.2 V and 1.0 V, turned into a slope and a time origin), so both
arms traverse the same ramp trajectory and the A/B isolates the ramp node's
*dynamics and source impedance*, not its rate. Fitting per point rather than
using one nominal slope matters because the ramp's own +/-25% poly-resistor
corner is exactly the axis a fixed slope would confound this comparison with.

The SSR port promotion is not reimplemented here: it is
`sim/soft-start-loop-gain/testbench/netlist_variants.py`'s
`instrument_core()`/`promote_ssr_port()` (issue #196), called directly, so the
repo keeps one implementation of it. The derived netlist is frozen next to the
logs.

Logs and the rollup CSV land under `sim/soft-start/corners/<record-id>-rampab/`.
Writing the record under `sim/soft-start/records/` is by hand, as with every
other bench here.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import csv
import datetime as _dt
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

HERE = Path(__file__).resolve().parent
EXPDIR = HERE.parent
REPO_ROOT = EXPDIR.parent.parent
LG_TB = REPO_ROOT / "sim" / "soft-start-loop-gain" / "testbench"

sys.path.insert(0, str(REPO_ROOT / "sim"))
sys.path.insert(0, str(LG_TB))

import netlist_variants as nv  # noqa: E402
from harness.corners import build_grid, resolve_corners  # noqa: E402
from harness.pdk import find_pdk  # noqa: E402
from harness.runner import (  # noqa: E402
    ngspice_binary_sha256,
    ngspice_version,
    run_ngspice_deck,
)

TEMPLATE = HERE / "tb_ss_ramp_ab.spice.in"
TOKEN_RE = re.compile(r"@([A-Z0-9_]+)@")
SPICEINIT = "set wnflag=1\nset num_threads=1\n"

# The corner set this experiment is named against. `tt_-40c_2.97v` is the
# corner `design/softstart_injection_compensation.md` section 4 states its
# 356x-vs-2.1x arithmetic at, and the corner issue #191's own A/B used; the
# other two bracket it in supply, which is the axis the uncascoded mirror's
# error was measured to track (0.917 V of ramp node per volt of supply).
NAMED_CORNERS = ("tt",)
NAMED_TEMPS = (-40.0,)
NAMED_SUPPLIES = (2.97, 3.30, 3.63)
# The nominal output network and the full rated load: the main matrix's own
# point, so the numbers are directly comparable with sim/soft-start's records.
DEFAULT_COUT = "1u"
DEFAULT_ESR = "0.1"
DEFAULT_RLOAD = "36"

# The two SSR crossings the PWL fit is taken between. Both are well inside the
# live part of the ramp: above the reset device's own decay tail at the bottom
# and below `Mtop_ss`'s ceiling at the top.
FIT_SSR_LO_V = 0.2
FIT_SSR_HI_V = 1.0

ARMS = ("internal", "ideal")

MEAS_RE = re.compile(r"^\s*(m_[a-z0-9_]+)\s*=\s*([-+0-9.eE]+|failed)", re.M)


@dataclass
class Point:
    corner_id: str
    corner: str
    temp_c: float
    vin_v: float
    cout: str
    esr: str
    rload: str


def parse_meas(text: str) -> dict[str, float | None]:
    out: dict[str, float | None] = {}
    for name, val in MEAS_RE.findall(text):
        out[name] = None if val == "failed" else float(val)
    return out


def render(point: Point, pdk, *, arm: str, netlist: Path, ssr_drive: str) -> str:
    corner = resolve_corners([point.corner])[0]
    mos, res, bjt, diode, moscap, mimcap = corner.sections
    subs = {
        "DESIGN_INCLUDE": str(pdk.design_include),
        "MODEL_LIB": str(pdk.model_lib),
        "LDO_NETLIST": str(netlist),
        "MOS_CORNER": mos, "RES_CORNER": res, "BJT_CORNER": bjt,
        "DIODE_CORNER": diode, "MOSCAP_CORNER": moscap, "MIMCAP_CORNER": mimcap,
        "TEMP_C": f"{point.temp_c:g}",
        "VIN_V": f"{point.vin_v:g}",
        "COUT": point.cout,
        "ESR_OHM": point.esr,
        "RLOAD_OHM": point.rload,
        "CORNER_ID": point.corner_id,
        "ARM": arm,
        "SSR_DRIVE": ssr_drive,
    }
    text = TEMPLATE.read_text()
    missing = {m for m in TOKEN_RE.findall(text) if m not in subs}
    if missing:
        raise SystemExit(f"template has unsubstituted tokens: {sorted(missing)}")
    return TOKEN_RE.sub(lambda m: subs[m.group(1)], text)


INTERNAL_DRIVE = (
    "* arm `internal`: nothing drives SSRPIN. The promoted port is left\n"
    "* unconnected, exactly as the loop-gain bench's `anchor` phase leaves\n"
    "* it, so this arm is electrically tb_soft_start.spice.in."
)


def ideal_drive(*, t0_s: float, slope_v_per_s: float, ceiling_v: float) -> str:
    """The PWL that reproduces the `internal` arm's ramp from an ideal source.

    Four breakpoints: held at 0 until the fitted time origin (the ramp's own
    release, which `Mdis_ss`/`SD` set), then linear at the fitted slope up to
    the `internal` arm's own settled ceiling, then flat. The ceiling is taken
    from the same arm rather than assumed, because `Mtop_ss`'s clamp level is
    itself PVT-dependent and holding the ramp somewhere else would change the
    injection element's own rectified end state, which is not what this A/B is
    varying.
    """
    t_ceiling = t0_s + ceiling_v / slope_v_per_s
    return (
        "* arm `ideal`: SSR is FORCED by an ideal PWL source on the promoted\n"
        "* port, fitted to THIS point's own `internal` arm (slope "
        f"{slope_v_per_s:.6g} V/s,\n"
        f"* origin {t0_s * 1e6:.4g} us, ceiling {ceiling_v:.6g} V). Fss_ramp,\n"
        "* Css, Mdis_ss and Mtop_ss are all still present and connected; an\n"
        "* ideal source simply absorbs whatever they push, so the ONLY thing\n"
        "* that differs from the `internal` arm is the ramp node's dynamics\n"
        "* and source impedance.\n"
        f"Vssr SSRPIN 0 PWL(0 0 {t0_s:.9g} 0 "
        f"{t_ceiling:.9g} {ceiling_v:.6g} 9m {ceiling_v:.6g})"
    )


def run_arm(point: Point, pdk, *, arm: str, netlist: Path, ssr_drive: str,
            workdir: Path, logdir: Path):
    stem = f"{point.corner_id}_{arm}"
    deck = workdir / f"{stem}.spice"
    deck.write_text(render(point, pdk, arm=arm, netlist=netlist,
                           ssr_drive=ssr_drive))
    log = logdir / f"{stem}.log"
    try:
        text = run_ngspice_deck(deck, log, workdir)
    except RuntimeError as exc:
        return None, str(exc)
    if f"SWEEP COMPLETE {point.corner_id} {arm}" not in text:
        return None, "deck did not reach its SWEEP COMPLETE marker"
    return parse_meas(text), None


def run_point(point: Point, pdk, *, netlist: Path, workdir: Path, logdir: Path):
    """-> (internal-measurements, ideal-measurements, fit, error-or-None)."""
    a, err = run_arm(point, pdk, arm="internal", netlist=netlist,
                     ssr_drive=INTERNAL_DRIVE, workdir=workdir, logdir=logdir)
    if err:
        return None, None, None, f"internal arm: {err}"
    t_lo, t_hi = a.get("m_ssr_t02"), a.get("m_ssr_t10")
    ceiling = a.get("m_ssr_end")
    if t_lo is None or t_hi is None or ceiling is None or t_hi <= t_lo:
        return a, None, None, (
            "internal arm did not produce a usable ramp fit "
            f"(t02={t_lo}, t10={t_hi}, ssr_end={ceiling})")
    slope = (FIT_SSR_HI_V - FIT_SSR_LO_V) / (t_hi - t_lo)
    t0 = t_lo - FIT_SSR_LO_V / slope
    fit = {"slope_v_per_s": slope, "t0_s": t0, "ceiling_v": ceiling}
    b, err = run_arm(point, pdk, arm="ideal", netlist=netlist,
                     ssr_drive=ideal_drive(**fit), workdir=workdir,
                     logdir=logdir)
    if err:
        return a, None, fit, f"ideal arm: {err}"
    return a, b, fit, None


FIELDS = ("m_icap_peak_ma", "m_icap_peak_acq_ma", "m_icap_peak_ramp_ma",
          "m_isup_peak_ma", "m_t_startup", "m_vout_settled", "m_vout_max_en",
          "m_dvout_max", "m_dvout_min", "m_vout_at_hr", "m_ssr_at_hr",
          "m_ssr_end", "m_hg_end", "m_t_v04", "m_t_v14")


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--corners", nargs="+", default=list(NAMED_CORNERS))
    ap.add_argument("--temps", nargs="+", type=float, default=list(NAMED_TEMPS))
    ap.add_argument("--supplies", nargs="+", type=float,
                    default=list(NAMED_SUPPLIES))
    ap.add_argument("--cout", default=DEFAULT_COUT)
    ap.add_argument("--esr", default=DEFAULT_ESR)
    ap.add_argument("--rload", default=DEFAULT_RLOAD)
    ap.add_argument("-j", "--jobs", type=int, default=4)
    ap.add_argument("--record-id", default="")
    args = ap.parse_args()

    pdk = find_pdk()
    check = subprocess.run(
        [sys.executable, str(REPO_ROOT / "design" / "netlist.py"), "--check"],
        capture_output=True, text=True)
    if check.returncode != 0:
        print("FATAL: design/netlist/*.spice is stale vs the schematics:",
              file=sys.stderr)
        print(check.stdout + check.stderr, file=sys.stderr)
        return 3

    short = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "rev-parse", "--short", "HEAD"],
        capture_output=True, text=True).stdout.strip()
    record_id = args.record_id or (
        _dt.datetime.now(_dt.timezone.utc).strftime("%Y%m%d-%H%M%S")
        + f"-{short}")

    logdir = EXPDIR / "corners" / f"{record_id}-rampab"
    logdir.mkdir(parents=True, exist_ok=True)
    workdir = REPO_ROOT / "sim" / ".work" / EXPDIR.name / f"{record_id}-rampab"
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / ".spiceinit").write_text(SPICEINIT)

    netlist = logdir / "ldo_core_ssrport.spice"
    netlist.write_text(nv.build_variant(REPO_ROOT, "device"))

    corners = resolve_corners(args.corners)
    grid = build_grid(corners, args.temps, args.supplies)
    points = [Point(corner_id=p.corner_id, corner=p.corner.name,
                    temp_c=p.temp_c, vin_v=p.vdd, cout=args.cout,
                    esr=args.esr, rload=args.rload)
              for p in grid]

    print(f"pdk           : {pdk.variant} @ {pdk.version}")
    print(f"ngspice       : {ngspice_version()}")
    print(f"ngspice sha256: {ngspice_binary_sha256()}")
    print(f"record id     : {record_id}-rampab")
    print(f"points        : {len(points)} x 2 arms")
    print(f"dut netlist   : {netlist}")
    print()

    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        futs = {pool.submit(run_point, p, pdk, netlist=netlist,
                            workdir=workdir, logdir=logdir): p
                for p in points}
        for done in concurrent.futures.as_completed(futs):
            p = futs[done]
            a, b, fit, err = done.result()
            results.append((p, a, b, fit, err))
            if err:
                print(f"  {p.corner_id:<20} ERROR {err}")
                continue
            print(f"  {p.corner_id:<20} "
                  f"icap_peak internal {a['m_icap_peak_ma']:10.4f} mA | "
                  f"ideal {b['m_icap_peak_ma']:10.4f} mA   "
                  f"(acq {a['m_icap_peak_acq_ma']:9.4f} -> "
                  f"{b['m_icap_peak_acq_ma']:9.4f} mA)")

    csv_path = logdir / "summary.csv"
    with csv_path.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["corner_id", "corner", "temp_c", "vin_v", "cout", "esr",
                    "rload", "arm", "fit_slope_v_per_s", "fit_t0_us",
                    "fit_ceiling_v", *FIELDS, "error"])
        for p, a, b, fit, err in sorted(results, key=lambda r: r[0].corner_id):
            for arm, meas in (("internal", a), ("ideal", b)):
                w.writerow([
                    p.corner_id, p.corner, p.temp_c, p.vin_v, p.cout, p.esr,
                    p.rload, arm,
                    "" if not fit else f"{fit['slope_v_per_s']:.6g}",
                    "" if not fit else f"{fit['t0_s'] * 1e6:.6g}",
                    "" if not fit else f"{fit['ceiling_v']:.6g}",
                    *[("" if meas is None or meas.get(f) is None
                       else f"{meas[f]:.6g}") for f in FIELDS],
                    err or "",
                ])
    print(f"\nrollup        : {csv_path}")
    print(f"raw logs      : {logdir}/")
    print(f"record-id     : {record_id}-rampab")
    print(f"(write {EXPDIR}/records/<id>.md by hand -- see sim/README.md)")
    return 0 if all(r[4] is None for r in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
